sudo: false

language: java

jdk:
  - openjdk11

install: mvn -B install -DskipTests=false

# https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
script: travis_wait 60 mvn -B verify -Dmaven.javadoc.skip=true

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master